### PR TITLE
OS.MM: Replace with new OS.Memory interface

### PR DESCRIPTION
**Pull request by mato**
Replace the OS.MM module with a new OS.Memory statistics interface modeled on the stdlib's Gc stat type. All units are now in the system word size rather than pages which are arch-specific and ill-defined.

The implementation takes care to account for the fact that on Solo5 backends the heap is shared with the stack, and a malloc() allocation on the heap will fail if the heap would grow to within 1MB of the stack.

Once we have settled that this interface is fine for mirage-xen, I will add an identical interface to mirage-solo5, thus unifying all non-unix backends.

### CODE REVIEW

**Comment by hannesm** [comment]
this looks fine to me -- my only remark is that I'd name the function `stat` (instead of `quick_stat` - I don't think there's plans to expose "expensive, detailed memory usage statistic" (I guess `mallinfo` would fit here since it walks over the memory) via this interface), and document that it is computationally not expensive and does not allocate (too much - it still allocates the record).

Since we're breaking the API, I'm in favour to rename MM to Memory, if this suits well.

**Comment by mato** [comment]
> this looks fine to me -- my only remark is that I'd name the function stat (instead of quick_stat - I don't think there's plans to expose "expensive, detailed memory usage statistic" (I guess mallinfo would fit here since it walks over the memory) via this interface)

That's actually why I called it `quick_stat`; to leave room for a future `stat` that uses `mallinfo()` or any other useful but slow interfaces to get more/accurate statistics.

> and document that it is computationally not expensive and does not allocate (too much - it still allocates the record).

I did that in `oS.mli`, feel free to suggest improvements. Not sure it's worth caring about the allocation of the record; if you can't allocate that, you're probably not going to be able to do anything else useful anyway?

> Since we're breaking the API, I'm in favour to rename MM to Memory, if this suits well.

Fine with me; if nothing else my brain will be less confused with the capitalization of the source files :-)

**Comment by hannesm** [comment]
Thanks for your prompt reply @mato. I'm fine with `quick_stat` after another thought. From my point of view, only a rename mM.ml -> memory.ml (and corresponding change in oS.mli / oS.ml) would be nice.

> I did that in `oS.mli`, feel free to suggest improvements. Not sure it's worth caring about the allocation of the record; if you can't allocate that, you're probably not going to be able to do anything else useful anyway?

Thanks, here would be my suggestion:

```
(** [quick_stat ()] returns memory allocation statistics. This call is computationally cheap, but
 * the returned values may not be completely accurate. *)
```

**Review by hannesm — APPROVED** [review]

**Comment by mato** [comment]
@hannesm Comments addressed, re-based and force-pushed.

**Review by talex5 — APPROVED** [review]
LGTM

**Pull request merged**
