### PR TITLE
topkg'ed

### PR DESCRIPTION
**Pull request by hannesm**

### CODE REVIEW

**Comment by hannesm** [comment]
thanks to @gasche in https://github.com/ocaml/ocamlbuild/issues/268

**Comment by hannesm** [comment]
please squash and merge, this works (i.e. compiles) with mirage-block-xen, mirage-net-xen, mirage-bootvar-xen,mirage-console-xen, mirage-qubes, nocrypto and vchan-xen -- revdeps should work out nicely in travis (some are uninstallabe, not sure whether travis handles that well)

**Comment by hannesm** [comment]
while revdep work, the final linking of a mirage unikernel fails with unknown symbols `xchg` and `__ffs`... will investigate later

**Comment by hannesm** [comment]
now with the help of @yomimono laptop again, I got the build system to be happy and a pin of this branch let's me build example mirageos unikernel (compile and link AND execute).  would be happy for some review or some pressing of green buttons :D

**Comment by hannesm** [comment]
force-pushed and wrote a commit message.. once CI is green, this is good to go (please, anyone press a green button)

**Comment by yomimono** [comment]
:tada: thanks very much for your work on this, @hannesm !

**Pull request merged**
