### PR TITLE
Revert "Merge pull request #16 from dune-universe/separate-api"

### PR DESCRIPTION
**Pull request by dinosaure**
This is a revert of a split of the library to keep an homogeneous design between `mirage-unix`, `mirage-solo5` and `mirage-xen`. Purpose of mirage/mirage-xen#16 is to follow a deep change constrained by `mirage-os-shim` and `mirage-entropy` but, according mirage/mirage#1010, we want to delete `mirage-os-shim`.

At the end, the split of the library is not needed anymore and we should revert this change.

### CODE REVIEW

**Comment by hannesm** [comment]
to me, the changes done in #16 to `bindings/dune` are good (less code), and we should not revert those in here, if possible. I'll have a look later with a computer that can actually build this package

**Comment by dinosaure** [comment]
It seems that, as expected, `REVDEPS` fails. Am I able to merge this PR and fill others now?

**Comment by hannesm** [comment]
@dinosaure sure -- I also PRed https://github.com/dinosaure/mirage-xen/pull/1 with more changes towards mirage 3.7.0 :) -- which allows to build mirage-skeleton in a 3.7.0 universe!

**Comment by dinosaure** [comment]
Ok, to avoid complexity, I merge this PR and prepare PR which include dinosaure/mirage-xen#1

**Pull request merged**
